name: Deploy

on:
    push:
        branches:
            - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                path: vendor
                key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-node-

            - name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            - name: Log in to the Container registry
                uses: docker/login-action@v2
                with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v4
                with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push image to GHCR
                uses: docker/build-push-action@v3
                with:
                context: .
                push: true
                platforms: ${{ env.PLATFORMS }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                tag_with_ref: true
